### ISSUE TITLE
FIX-EPIC-見積もりに関わる改修

### ISSUE THREAD

**Issue by Lorenzras** [cocosumo/yumecoco-monorepo#1091]
## 改修タスク

- [x] #1088
- [x] #1090 
- [x] #1105
- [x] #1094
- [x] #1099
- [x] #1112
- [x] #1097
- [x] #1113
- [x] #1089

**Comment by Lorenzras** [comment]
@YokoHayakawa 

単独タスクはOKになったら、リグレッションテストをよろしくお願いいたします。

**Comment by YokoHayakawa** [comment]
リグレッションテスト実施しました。
nは足りていないかもしれませんが、確認した限りでは問題ないと思います。

**Comment by Lorenzras** [comment]
ありがとうございます。次は、ユーザからフィードバックを頂きましょう。

**Comment by Lorenzras** [comment]
大井さんに進捗状況をチャットで伝えました。
一緒に試せるといいですね。

**Comment by Lorenzras** [comment]
2024.03.19、帰りに、大井さんにフィードバックをいただくために、テストをお願いしました。

受発注には見積もり入力から派生する機能もありますので、これが土台となります。

これをクリアしたら、受発注の開発がスムーズになります。

**Comment by Lorenzras** [comment]
@YokoHayakawa @kana-takahashi0705 

フィードバック頂く次第、改修となります。他タスクへ移ります。

よって、当Isuue閉じさせて頂きます。
