### ISSUE TITLE
行の追削が分かりづらい

### ISSUE THREAD

**Issue by Lorenzras** [cocosumo/yumecoco-monorepo#1111]
## タスク

行の追加削除が選べるメニューボタン（…や+のようなもの）を行の右端に配置する

- [x] 行追加
- [x] コピー
- [x] 削除

**Comment by Lorenzras** [comment]
@YokoHayakawa 

テストありがとうございます！　ISSUEに変更しました。

具体的にどのように分かりやすくなるんでしょうか。

**Comment by Lorenzras** [comment]
> 視覚的に説明なくわかるのがベストだと思っています。 行の追加削除が選べるメニューボタン（…や+のようなもの）を行の右端に配置するのはどうでしょう？

同じ考えで安心しました。ｗ

この間、大井さんに同じようなことを提案しましたが、
ボタンを増やすより、分かりやすいホットキーが望ましいとのことです。

大黒さんの慣れで、見積もりを入力するとき、 `Fキー`を利用して、マウスをあまり使わないかもしれません。

今のキーの設定は、[依頼](https://rdmuhwtt6gx7.cybozu.com/k/236/show#record=4)で実装しましたが、
ソースで簡単に変えられるようになっています。

でも、たたき台として、実装します！ありがとうございます。

**Comment by Lorenzras** [comment]
> @Lorenzras あと、ショートカットキーで行の挿入をしたときに、選択している行の1行上に入ってしまっていました。 基本的に入力はどんどん下に続けていくと思うので、下に挿入していく方が良いのでは？という印象です。
> 
> とはいえ、いろんな意見があると思うので、使用するユーザーの意見優先で大丈夫です。

ありがとうございます。#1113　と関連すると思いますので、そこで挙動を明確にします。m(__)m

**Comment by YokoHayakawa** [comment]
>同じ考えで安心しました。ｗ
この間、大井さんに同じようなことを提案しましたが、
ボタンを増やすより、分かりやすいホットキーが望ましいとのことです。

私も同じ考えだとわかって安心しました。
ユーザー意見なんですね！

>でも、たたき台として、実装します！ありがとうございます。

実装了解です！ありがとうございます。
よろしくお願いします！

**Comment by Lorenzras** [comment]
@YokoHayakawa 

対応に優先度低いようで、単独ISSUEにしました。

**Comment by Lorenzras** [comment]
keep alive

**Comment by Lorenzras** [comment]
@YokoHayakawa @kana-takahashi0705 

以下で解決済み。

#1454 
#1455 
#1179
