### ISSUE TITLE
見積のキー入力モードが半角英数字になってしまう

### ISSUE THREAD

**Issue by YokoHayakawa** [cocosumo/yumecoco-monorepo#1161]
## 内容

- 見積のキー入力モードが、入力フィールドに合わせて全角から半角英数には変化するが、逆には変化しない
- 具体例：一番左(大項目)にカーソルがある状態は全角(ひらがな)で、右に送っていくと原価入力時に半角英数字になる
- そのまま右に送って行って単位や備考欄、次行になっても半角英数字のままになってしまっている

## 回避策

- PCの入力設定で、レガシーを使用すれば自動で変更される

**Comment by Lorenzras** [comment]
再現性を詳しく記載して頂いて、ありがとうございます！

対応してみます。何かいい方法をあれば、教えて下さい。

**Comment by YokoHayakawa** [comment]
IME設定で修正できるということはバグ？とも思うので、優先度下げても良いのかなと思いました。
![image](https://github.com/cocosumo/yumecoco-monorepo/assets/87287796/92bcff24-8bfd-408a-9b46-b4d3b04e20b5)
それはそれとして、対応策が無いか確認してみます！

**Comment by Lorenzras** [comment]
郵便番号の入力の時にもやりましたが、行けるかな。

インプットの type はnumberではなく、textにすれば、全角・半角勝手に切り変わらないです。
入力後、半角数字になるように処理を実装します。

**Comment by YokoHayakawa** [comment]
対応ありがとうございます！

調べてみましたが、そのものずばりな対策は見つかりませんでした。
ベターな対応として見つけられたのが、ラスさんがPRで立ち上げてくれたような、フォーカスが外れたとき(今回だと次のセルに移動する時)に全角→半角に変換するような対策でした。

なので、現状この対策で問題ないと思います。
また問題が出てきたタイミングで、その時のより良い対策を探していくしかないかな、という印象です。

**Comment by Lorenzras** [comment]
よかった。ありがとうございます。Kintoneも同じ対策をやっています。

ただし、フィールドにフォーカスが入り、入力中にマウスのクリックでフォーカスを外したら、ダブってしまいます。

個人的にはやり勝ちな操作で、日本の方の視点はいかがでしょうか。

**Comment by YokoHayakawa** [comment]
@Lorenzras 
>ただし、フィールドにフォーカスが入り、入力中にマウスのクリックでフォーカスを外したら、ダブってしまいます。

個人的な話でいうとあまりやらないですが、マウス多用する人は多いと思うので、使用者からバグ報告としてあがってくる可能性はあるかなと思います。

ただ、その操作を意図的にやってみましたが、2,3回連続でやらないと発現しませんでした。
それよりは、入力→Enter→マウスクリックでフォーカスを外すと、入力中の内容(数値)が消えてしまうことが気になりました。(※1)
入力してからマウス操作する前にEnter(変換の確定)してセル移動(Enter or Tab)しないと入力がうまくいかないので、
よほどこのバグは発現しないのではないかという印象です。

※1の現象を対策するかどうかは別途。

認識違うところがあれば教えてください
