### ISSUE TITLE
担当者は発注登録の入力が出来る

### ISSUE THREAD

**Issue by Lorenzras** [cocosumo/yumecoco-monorepo#1208]
## 完了するためのタスク

- [x] #1220
- [x] #1215
- [x] #1216
- [x] #1217
- [x] #1219
- [x] #1218 

##  備考

発注は含まない。

**Comment by Lorenzras** [comment]
見積もりから引用は別タスク機能としてやります。

**Comment by Lorenzras** [comment]
@YokoHayakawa 

強制マージしました。ご確認お願いします。

チェックは手動です。

バグ系はここで対応しましょう。

変更・追加機能は別の[ユーザストリー](https://spice-factory.co.jp/development/user-story/)として対応します。
優先度に応じて、当Iterationで対応します。

**Comment by YokoHayakawa** [comment]
細かいところになってしまいますが、
ページ全体としての横スクロールバーが常に表示されているので、
発注詳細の横スクロールバーが表示されていない時に、どうやって発注の右のほう見るのかが少し戸惑いました。
すぐに気づく問題だとは思いますが、ページの方の横スクロールバー非表示にしておいた方が
視覚的に誤解を生まないかなと感じました。

![スクリーンショット 2024-04-01 103940](https://github.com/cocosumo/yumecoco-monorepo/assets/87287796/eaaf7cfa-4348-4381-9192-1cf445d35753)

**Comment by YokoHayakawa** [comment]
数量に数値を入れて、保存or登録しようとしたら、このようなエラーが出てしまいました。
細かいところですが、「。。」で。が二つの誤記修正も併せて対応したいですね。

![image](https://github.com/cocosumo/yumecoco-monorepo/assets/87287796/21eae4f8-1bd7-43bf-97b6-3976cc014ef2)

**Comment by Lorenzras** [comment]
> 細かいところになってしまいますが、 ページ全体としての横スクロールバーが常に表示されているので、 発注詳細の横スクロールバーが表示されていない時に、どうやって発注の右のほう見るのかが少し戸惑いました。 すぐに気づく問題だとは思いますが、ページの方の横スクロールバー非表示にしておいた方が 視覚的に誤解を生まないかなと感じました。
> 
> ![スクリーンショット 2024-04-01 103940](https://private-user-images.githubusercontent.com/87287796/318316557-eaaf7cfa-4348-4381-9192-1cf445d35753.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjEzOTEsIm5iZiI6MTcxMTk2MTA5MSwicGF0aCI6Ii84NzI4Nzc5Ni8zMTgzMTY1NTctZWFhZjdjZmEtNDM0OC00MzgxLTkxOTItMWNmNDQ1ZDM1NzUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA4NDQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlZmMyM2NkN2MzNDA4Yzc0OWJmYWY1MmJmYWQwZTk1ZTg2MDA5YjBlYjA0ZmRlNjU0NDM1MDgzMjIyNTU2ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dolIaLZDUTIxjyRfsrySQ2GWNW5Pg_yvhKUY4ZJqSf8)

ありがとうございます！　画面を大きく見たい意見がありましたので、スクロールはリリース後のユーザの意見を聞いて修正しましょう。

よって、P2優先としてバックログに追加しました。
https://github.com/orgs/cocosumo/projects/8/views/1?pane=issue&itemId=58236454

**Comment by Lorenzras** [comment]
> 数量に数値を入れて、保存or登録しようとしたら、このようなエラーが出てしまいました。 細かいところですが、「。。」で。が二つの誤記修正も併せて対応したいですね。
> 
> ![image](https://private-user-images.githubusercontent.com/87287796/318317513-21eae4f8-1bd7-43bf-97b6-3976cc014ef2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjE1ODMsIm5iZiI6MTcxMTk2MTI4MywicGF0aCI6Ii84NzI4Nzc5Ni8zMTgzMTc1MTMtMjFlYWU0ZjgtMWJkNy00M2JmLTk3YjYtMzk3NmNjMDE0ZWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA4NDgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5OTBmMWQ3NTcyZGQ5NWYyNGRiYzc2MjhhZmVhM2U0NWJmNWNjMzFiNjkwZWVjNzUwMmVmM2NhMzBkOGRkM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.609T2jByUg1YtK_E1LlVOTWw4i_MRZpzc_3W-JRMiYs)

ありがとうございます！
対応しました！ご確認お願いします。

**Comment by Lorenzras** [comment]
@YokoHayakawa 完了したら、Doneへの移動お願いします。

**Comment by YokoHayakawa** [comment]
@Lorenzras 
動作確認し、バグが解消されていることを確認しました。
