### ISSUE TITLE
担当者は発注登録へ見積から引用出来る

### ISSUE THREAD

**Issue by Lorenzras** [cocosumo/yumecoco-monorepo#1236]
## 完了条件

- [x] 「見積もりから引用」を押下すると見積もりのメニューが出る
- [x] 選択された見積を追加コピーされます。

## 備考

元の仕様は上書きでしたが、高橋さんに確認したところ、「発注済」に影響が出ないように、コピーのほうがシンプルでいいとのことでした。

なお、別アイディアが出たら、バックログに追加。

**Comment by Lorenzras** [comment]
@YokoHayakawa @kana-takahashi0705 

ステージングに実装します。

確認よろしくお願いいたします。
行の操作ボタンなどは別タスクで対応します。

**Comment by Lorenzras** [comment]
@YokoHayakawa 確認よろしくお願いします！

**Comment by YokoHayakawa** [comment]
[見積から引用]ボタンの挙動を確認しました。
動作に問題ないと思います。
ご対応ありがとうございます！

**Comment by Lorenzras** [comment]
ありがとうございます！
