### ISSUE TITLE
発注登録画面で担当者はボタンで複数削除が出来る

### ISSUE THREAD

**Issue by Lorenzras** [cocosumo/yumecoco-monorepo#1239]
## 完了条件

- [ ] Figmaを参考に、ボタンを配置する。
- [ ] 選択がなかったら、削除ボタンは無効化
- [ ] 削除を押したら、確認画面が出る。

**Comment by Lorenzras** [comment]
@kana-takahashi0705 @YokoHayakawa 

複数行削除ボタンはどこに配置しましょうか。

出来れば、Figmaでお願いします。

**Comment by kana-takahashi0705** [comment]
@Lorenzras 
発注登録画面（編集画面）でどうでしょう？
https://www.figma.com/file/bAQxkiU0B4ZLLlo4j5rOXP?type=design&node-id=23-117&mode=design#759726332
Figmaにフィールドとメモ付けました！

**Comment by Lorenzras** [comment]
> @Lorenzras 発注登録画面（編集画面）でどうでしょう？ https://www.figma.com/file/bAQxkiU0B4ZLLlo4j5rOXP?type=design&node-id=23-117&mode=design#759726332 Figmaにフィールドとメモ付けました！

了解です！一旦、処理を実装して、ボタンの配置は柔軟に変えられるようにします。
