### ISSUE TITLE
発注依頼の入力が表示される。

### ISSUE THREAD

**Issue by Lorenzras** [cocosumo/yumecoco-monorepo#1244]
## タスク

- [x] 項目を選択し、「発注書作成」を押したら、発注依頼画面が出る。
- [x] 選択した項目を、発注依頼画面に反映される。
- [x] Figmaを元にして、フィールドが表示される。

PRが大きくなるので、表示のみになりました。
挙動やバリデーションや保存を #1243 で対応します。

**Comment by YokoHayakawa** [comment]
達成しているタスクにチェック入れさせてもらいました。
