### ISSUE TITLE
発注依頼で入力した内容を生成した発注書に反映する (PDF)。

### ISSUE THREAD

**Issue by Lorenzras** [cocosumo/yumecoco-monorepo#1247]
## タスク

単体テスト出来るように、関数を作成します。

- [x] テンプレートをAWSのS3にアップロード 
- [x] #1357
- [x] #1349
- [x] #1351
- [x] #1358

`OrderData` の型は必要に応じて構築します。`generatePlanContract` が参考になります。

**Comment by Lorenzras** [comment]
@YokoHayakawa 

それぞれ関数ファイルのパスは　`packages\kokoas-server\src\handleRequest\reqDownloadOrderToSupplier`　いかがですか。

AWS S3へのアップロードですが、アカウントのログインに困ったら、一緒にやりましょう。
とりあえず、テンプレートはローカルから、取得してもいいです。

**Comment by Lorenzras** [comment]
@YokoHayakawa 

発注DBの構成がほぼ確定しました。getOrderDataの変換処理も可能になりました！変換処理の際にDB構成を変更する必要がある場合があるかもしれません。その際は一緒に検討しましょう。

**Comment by YokoHayakawa** [comment]
実装完了しました
