### ISSUE TITLE
発注依頼で、発注方法はメールの場合、担当者と業者へ添付して飛ぶ。

### ISSUE THREAD

**Issue by Lorenzras** [cocosumo/yumecoco-monorepo#1249]
# 完了条件

- [x] 発注方法はメールの場合、開発環境のメールに、添付飛んでいること。
- [x] 操作が完了したこと、ユーザ分かること。
- [x] 開発環境でテスト用の発注先ありこと。
- [x] テスト用の発注先に送信されていること。

本番環境のテストでは、テスト用の発注先を利用ください。

**Comment by Lorenzras** [comment]
@YokoHayakawa @kana-takahashi0705 

今Iterationでは間に合わないので、次のIterationで対応します。

https://github.com/orgs/cocosumo/projects/8/views/2?sliceBy%5Bvalue%5D=Iteration+2

**Comment by YokoHayakawa** [comment]
@YokoHayakawa 
メモ：
masterにて動作確認中、[発注書発行]時にステータス変更が確認できない。
https://rdmuhwtt6gx7.cybozu.com/k/319/show#record=105

発注書発行をクリックした際、メールと添付は確認済
以下について確認する
1. 操作完了が確認できない(分からない)
2. ステータスが空のままで、遷移しない

**Comment by Lorenzras** [comment]
@YokoHayakawa 

ありがとうございます！

分割しようと思いましたが、別の問い合わせが来て、完了条件の記入すら出来ませんでした。

すみません、別PRで完了させます。
新しい
