### ISSUE TITLE
発注登録画面で追加と削除のホットキーを変更する

### ISSUE THREAD

**Issue by Lorenzras** [cocosumo/yumecoco-monorepo#1256]
## 完了条件

- [x] Alt+v（追加）
- [x] Alt+b（削除）

https://www.figma.com/file/bAQxkiU0B4ZLLlo4j5rOXP?type=design&node-id=23-117&mode=design#760008658

**Comment by Lorenzras** [comment]
@kana-takahashi0705 

[ステージング](https://rdmuhwtt6gx7.cybozu.com/k/177/#/project/order/input)へ実装しました。

確認お願いします。

**Comment by kana-takahashi0705** [comment]
@Lorenzras 
ありがとうございます！
部材は選択肢ないので、「選択↓」不要です！

しまった、、「Alt+v」コピーでした💦
「Alt+v」追加
「Shift+v」で追加コピーでいかがでしょう？

**Comment by kana-takahashi0705** [comment]
@Lorenzras 
あとセル選択状態で「Delete」したら十字キーが使えなく（画面がスクロールされるように）なりました💦
Enterも効かないので、マウスでクリックしないとダメみたいです。。

**Comment by Lorenzras** [comment]
@kana-takahashi0705 

確認ありがとうございます！再開しました。

[KT](https://bizx.chatwork.com/knowledge-management/knowledge-transfer/)のため, @YokoHayakawa  と一緒に対応しましょう。

**Comment by Lorenzras** [comment]
@kana-takahashi0705 @YokoHayakawa 

行を削除したら、入力テーブルにフォーカスが無くなる現象を #1261で修正してみます。

ホットキーの修正の対応はどうしましょうか？

将来的に固定せずに画面上で管理者が設定出来るようにするのもいいと思いますが、工数は10時間ぐらい増えます。

**Comment by kana-takahashi0705** [comment]
@Lorenzras 
> 行を削除したら、入力テーブルにフォーカスが無くなる現象を #1261 で修正してみます。

お願いします！

> ホットキーの修正の対応はどうしましょうか？

頻繁に使う動作（追加、コピー、削除）は優先度高めでお願いしたいです。
それ以外はその都度優先順位決めた方が良いかな…？

> 将来的に固定せずに画面上で管理者が設定出来るようにするのもいいと思いますが、工数は10時間以上増えます。

システム側の対応で良いと思います。
恐らくうちの人達で自ら率先してホットキーを設定しようという人は私くらい…笑
人によって使用感が違うのは当然なので、自由に設定できるようにすると恐らく戦争になる。笑
（ブラウザに依存するタイプにすればいいんでしょうけど、工数は絶対増えますし、うちの人達が自分で設定したホットキーを覚えていられるかは謎…w）

**Comment by Lorenzras** [comment]
@kana-takahashi0705 

了解です！

ホットキーの件、手が空いたら、@YokoHayakawa さんと対応お願いしてもいいですか。

**Comment by Lorenzras** [comment]
4月は22日の対応ということで、次のIterationに変更させてもらいました。 :truck:
