### ISSUE TITLE
発注依頼のサマリーで正しい数字を表示される

### ISSUE THREAD

**Issue by Lorenzras** [cocosumo/yumecoco-monorepo#1271]
## 派生元

- #1284 がマージされたら、チェックをお願いします。

## 完了条件

項目にある数字を計算し、正しい数字が表示される。

- [x] A 小計 10%対象：税抜金額の合計
- [x] B 消費税：課税の税抜金額を合計し、税率をかけた数字。
- [x] C 非課税 
- [x] 合計 = A + B + C
- [x] 位置などはFigmaに沿って実装。

**Comment by Lorenzras** [comment]
@YokoHayakawa 林さんから、Figmaを見ながら、外見と内容を修正しました。

**Comment by YokoHayakawa** [comment]
@Lorenzras 
サマリーの表示、確認しました。問題ないと思います！

**Comment by Lorenzras** [comment]
> @Lorenzras サマリーの表示、確認しました。問題ないと思います！

確認ありがとうございます！クロースをお願いします。

**Comment by YokoHayakawa** [comment]
完了条件の達成を確認したため、クローズします
