### ISSUE TITLE
発注依頼の項目入力の挙動は発注登録画面と同じである。

### ISSUE THREAD

**Issue by Lorenzras** [cocosumo/yumecoco-monorepo#1283]
## 完了条件

- [x] 入力した内容をDevtoolsに反映する。
- [x] 基本となる動作が出来る。編集・セル移動操作

**Comment by Lorenzras** [comment]
1283 発注依頼の項目入力の挙動は発注登録画面と同じである

@YokoHayakawa 

早川さんが次来るまで、日が空くので、深くならないように、強制マージさせて頂きます。

また、見積と発注依頼と発注登録と請求確認画面で、共通する挙動があるので、リファクタリングをします。

**Comment by YokoHayakawa** [comment]
承知しました！
よろしくお願いします。

**Comment by Lorenzras** [comment]
@YokoHayakawa 

- #1291 のリファクタリングで、当ISSUEはStaleになりました。

当ISSUEを閉じさせていただきます。確認は #1291 でよろしくお願いします。 
他に不明点があれば、声かけください！
