### ISSUE TITLE
データーグリッドのリファクタリング

### ISSUE THREAD

**Issue by Lorenzras** [cocosumo/yumecoco-monorepo#1291]
##  完了条件

- [ ] `見積`、`発注入力`、`発注依頼`のデータグリッドのホットきーのコードを統一化しました。

## 備考

変更や修正が多い機能のようで、コードのみ統一化します。それで、コードの変更は一カ所で済みます。
なお、挙動自体の修正の対応は @YokoHayakawa と @kana-takahashi0705 にお願いしています。

**Comment by YokoHayakawa** [comment]
@Lorenzras 
#1283 で残っていた動作の確認を完了し、問題ありませんでした。
```
packages\kokoas-client\src\pages\order\orderRequestForm\orderDialogContent\orderItems\useDataGridKeyCellKeyDown.ts
```
こちら、ファイルは残っていますが、deprecatedもしくはファイル削除しなくても良いでしょうか？

**Comment by Lorenzras** [comment]
> @Lorenzras #1283 で残っていた動作の確認を完了し、問題ありませんでした。
> 
> ```
> packages\kokoas-client\src\pages\order\orderRequestForm\orderDialogContent\orderItems\useDataGridKeyCellKeyDown.ts
> ```
> 
> こちら、ファイルは残っていますが、deprecatedもしくはファイル削除しなくても良いでしょうか？

ありがとうざいます！削除したほうがいいですね。  #1295　で対応しました。確認よろしくお願いします。
