### ISSUE TITLE
担当者はメニューの請求管理をクリックしたら、請求一覧を閲覧出来る

### ISSUE THREAD

**Issue by Lorenzras** [cocosumo/yumecoco-monorepo#1362]
## 完了条件

- [x] #1390
- [x] #1391
- [x] #1394
- [x] #1397
- [x] #1399
- [x] #1400

**Comment by Lorenzras** [comment]
@YokoHayakawa @kana-takahashi0705 

優先度を上げました。

**Comment by Lorenzras** [comment]
@YokoHayakawa @kana-takahashi0705 

ほぼ強制マージなので、一括で挙動確認でお願いします！

コードに不備や改修あればはPRを立ち上げて頂けると助かります！

よろしくお願いします。

**Comment by YokoHayakawa** [comment]
@Lorenzras 
請求一覧の動作を確認しました。
強制マージ分の項目に関しては、issuesの達成条件のチェック入れさせてもらっています。

1点、確認していて、デフォルトの請求日の開始日と終了日の範囲が広いのが気になりました。
デフォルトは空にして全件表示したほうがベターかなと思いました。
修正はユーザに触ってもらって、実際に使う方々の意見を聞いてからでも良いかなと思います。
とりあえずはこの後issuesに入れておきます。

**Comment by Lorenzras** [comment]
@YokoHayakawa

チェックありがとうございます！

私も迷い変更想定でソースコードにコメントを残しました。ｗ
https://github.com/cocosumo/yumecoco-monorepo/pull/1401/files#diff-dd4d03ae1e84ea683724c702d4a59a70ababd56b83bb2148e30ecef8a198bfce

簡単な改修ですが、システム負荷を考慮しないと行けないですね。
