### ISSUE TITLE
工事依頼書発行時に、注文請書の発行を追加します

### ISSUE THREAD

**Issue by YokoHayakawa** [cocosumo/yumecoco-monorepo#1387]
## 内容

- 正式な手続きでは必要となるため、工事依頼書発行時に合わせて注文請書も発行します
- フロントエンドでは、工事依頼書発行時に、発行書類を選択(両方or工事依頼書のみ)できるようにしてほしいとのこと

**Comment by YokoHayakawa** [comment]
@Lorenzras 
まずは工事依頼書と注文請書の両方が発行されるパターンのみで実装します。
発行書類の選択は後追いで対応しましょう！

**Comment by Lorenzras** [comment]
ありがとうございます。了解です。優先度　P2 で　設定しました。
どのIterationに対応できるか、検討しましょう。

優先度についてシンプル化したものですが、必要に応じて定義を調整しましょう。
https://github.com/orgs/cocosumo/projects/8?pane=info

**Comment by YokoHayakawa** [comment]
@Lorenzras 
了解です！
現状の進捗状況から、一旦iteration 5 で設定させてもらいました。
