### ISSUE TITLE
発注依頼画面で、発注の「差し戻し」と「削除」が出来る。

### ISSUE THREAD

**Issue by Lorenzras** [cocosumo/yumecoco-monorepo#1430]
## 完了条件

- [x] #1431
- [x] #1432
- [x] #1434
- [x] #1436
- [x] #1443
- [x] #1445

## 備考

取り消しをしたら、発注データも削除される仕様になります。
経理から要望で、発注又は請求が進行中でも、修正可能になっています。
担当者自身が変更を業者に伝えるのが現状だそうです。

もし、取り消された発注データを残す仕様に変わったら、工数は16ぐらい見込みます。現在の工数は8です。

**Comment by kana-takahashi0705** [comment]
Figmaに追加メモさせてもらいました！
https://www.figma.com/design/bAQxkiU0B4ZLLlo4j5rOXP?node-id=322-2198#824515962
「請求承認済を押したら「差し戻し」は不可にする」

そこまで（本社に飛ぶ前まで）は「差し戻し」可で。

削除データは保存なしで良いでしょう。
たぶんデータ量も膨大になってどれがどれか見分けもつかなくなってしまうでしょうし。
なので、「取り消し」よりかは「削除」の方が良いかもですね。
削除ボタン押下後、ポップアップ警告で
「削除するとデータは完全に消え復元できません。削除しますか？」⇒いいえ / はい
と入れれば良いと思います。

**Comment by Lorenzras** [comment]
了解です！では、完了条件を調整します。

**Comment by Lorenzras** [comment]
> 「請求承認済を押したら「差し戻し」は不可にする」

了解です。#1432 で対応します！

**Comment by Lorenzras** [comment]
@kana-takahashi0705 @YokoHayakawa 

#1446 がマージされたら、当ISSUEのレビュー・動作の確認をお願いします！

マスタへコミット済みのコードにも改善策があれば、PRかIssueをお願いします！

どうぞよろしくお願いします。

**Comment by YokoHayakawa** [comment]
@Lorenzras 

#1446 と合わせて、動作確認を行いました。
1点、修正したほうが良さそうな内容を確認しました。
issues #1457 にまとめましたので、ご確認をお願いいたします。

**Comment by Lorenzras** [comment]
@YokoHayakawa 
#1457 の確認ありがとうございます。当Issueは閉じて大丈夫でしょうか。

**Comment by YokoHayakawa** [comment]
@Lorenzras 
閉じるの忘れてましたね。
大丈夫なので、このまま閉じさせてもらいます！
