### ISSUE TITLE
発注書を差し戻した際、発注登録画面の一覧では「発注済」のままになっている

### ISSUE THREAD

**Issue by YokoHayakawa** [cocosumo/yumecoco-monorepo#1457]
## 内容

- 発注書を「差し戻し」した後、発注書発行画面上では「未発注」となる
- 工事の発注一覧画面に戻ると、「発注済」のままになってしまっている

## 対策

- [ ] 差し戻しした際、発注一覧画面側でも「未発注」の状態に戻す

**Comment by Lorenzras** [comment]
あら、ありがとうございます！まず再現してみます。
