### ISSUE TITLE
bug-見積もり画面で原価、数量、単価を入力したときに、原価金額が計算されていない

### ISSUE THREAD

**Issue by YokoHayakawa** [cocosumo/yumecoco-monorepo#1482]
- [x] 原価、数量、単価を入力したときに、粗利率、原価金額、税抜金額を計算する

デバッグ中に発見しました。
現状(6/19時点)、粗利率と税抜金額は計算されましたが、原価金額が0のままになっていました。
数量を入れなおしたら正しく計算されました。

**Comment by Lorenzras** [comment]
いい発見ですね！ありがとうございます。

ちょうど、眺めのいい席を取れたので、今から、優先に対応します！

まず、再現してみます。

**Comment by Lorenzras** [comment]
@YokoHayakawa 

レコード新規の時、1行目に再現出来ました。
２行目以降、再現出来ませんでした。

レコード編集の時、再現出来ませんでした。

もし、ユーザから報告があれば、早川さんが仰ったように、修正するまで、数量を操作させる案内になります。

クリティカル性が低く、修正に必要な工数も低いので、オンボーディングにいい練習になります。

でも、Assigneeは設定されていないので、勝手に対応します！

**Comment by Lorenzras** [comment]
@YokoHayakawa 

修正を入れなくても、数量と単価を入れれば、粗利率が計算されます。
完了条件として、満たしていると思いますが、いかがでしょうか。

尚、関連する別バグを気付いて、#1486で修正しました。w

勘違いがあれば、再現の手順を教えていただければ、助かります。

どうぞよろしくお願いします。

**Comment by YokoHayakawa** [comment]
@Lorenzras 
現状確認して頂いてありがとうございます！
昨日は都合で出勤時間が短かったため、慌ててissue残しただけになってしまったので、
いじわる問題出して逃げたみたいになってしまいましたね…
私も気付いていなかった細かな条件がわかって、とても助かりました！

こちらでも改めてあまり想定していなさそうな入力手順をいくつか試してみましたが、
試した限りでは問題ありませんでした。
ご対応ありがとうございます！

**Comment by Lorenzras** [comment]
@YokoHayakawa 

大丈夫です。再現性の記載は十分でした。

確認、ありがとうございます！
