### ISSUE TITLE
bug-見積を取得の際にコンソールでエラーが出ます。

### ISSUE THREAD

**Issue by Lorenzras** [cocosumo/yumecoco-monorepo#1501]
## 調査

- 初段階調査では新規の場合のみ、再現出出来ました。

## 原因

- 空のestimateIdによってレコードがundefinedになり、計算の際にエラーが発生していました。

##　修正するまでユーザにおすすめ行動

- 不要。react-queryのエラーハンドラーにより、アプリケーションがクラッシュすることはなく、操作に影響することも確認されませんでした。

## 内容

```
TypeError: Cannot read properties of undefined (reading 'value')
    at calculateEstimateRecord (calculateEstimateRecord.ts:15:26)
    at eval (useEstimateById.ts:18:71)
    at Generator.next (<anonymous>)
    at fulfilled (tslib.es6.mjs:153:56)
```

**Comment by Lorenzras** [comment]
@YokoHayakawa 

新規でしか再現出来ませんでした。早川さんの方はいかがでしょうか。

**Comment by YokoHayakawa** [comment]
@Lorenzras 
きちんと覚えていないので、月曜に確認して連絡させてもらいます。

**Comment by Lorenzras** [comment]
@YokoHayakawa 

一応、#1503 修正を入れました。他に原因があれば、お知らせください。修正します！

**Comment by YokoHayakawa** [comment]
@Lorenzras 
修正ありがとうございます！
この現象の再現条件を確認しましたが、ラスさんと同じく、新規のみで発生しているようでした。
#1503 では修正されていることも確認しました。ありがとうございます！
