### ISSUE TITLE
請求項目と金額が空だと保存できないようにする

### ISSUE THREAD

**Issue by YokoHayakawa** [cocosumo/yumecoco-monorepo#1506]
invoiceDetails = invoiceDetail[]としてschemaに定義

invoiceDetailsの要素数は1以上、
invoiceDetailの中身で項目名が設定されているのに金額が空の場合はエラーになるように設定

→
初期値で配列要素を1つ設定しているため、バリデーションがうまく働かない

**Comment by YokoHayakawa** [comment]
@Lorenzras 
請求書の保存処理のバリデーションがうまく設定できずに悩んでいます。
「保存」ボタンを押した時に、請求金額が一つも入力されていなければエラーで保存できないようにしたいのですが、
何かいい案あればご教授お願いいたします。

**Comment by Lorenzras** [comment]
わかりました。どんなエラーか、PRの方で見ます。

**Comment by YokoHayakawa** [comment]
@Lorenzras 
確認ありがとうございます！
PRの方で内容確認して対応させていただきます。
